name: treeco
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^3.1.0
  cupertino_icons: ^1.0.2
  geolocator: ^9.0.2
  fluttertoast: ^8.2.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.16
  flutter_image_slideshow: ^0.1.5
  path_provider: ^2.0.11
  google_sign_in: ^6.1.0
  image_picker: ^0.8.6+1
  share_plus: ^6.3.0
  sqflite: ^2.2.8+2
  archive: ^3.3.7
  camera: ^0.10.1
  uuid: ^3.0.7
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/recursos/icones/
    - lib/recursos/imagens/
    - lib/recursos/estaticos/
    
flutter_icons:
  ios: true
  android: true
  image_path_ios: "lib/recursos/icones/ios-icon.png"
  image_path_android: "lib/recursos/icones/icon.png"
  adaptive_icon_background: "lib/recursos/icones/background.png"
  adaptive_icon_foreground: "lib/recursos/icones/foreground.png"    

