name: treeco
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^3.1.0
  cupertino_icons: ^1.0.2
  geolocator: ^9.0.2
  fluttertoast: ^8.2.1
  flutter_native_splash: ^2.2.16
  google_sign_in: ^6.1.0
  image_viewer: ^1.5.0
  camera: ^0.10.1
  uuid: ^3.0.7
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/recursos/icones/
    - lib/recursos/imagens/
    
flutter_icons:
  ios: true
  android: true
  image_path_ios: "lib/recursos/icones/ios-icon.png"
  image_path_android: "lib/recursos/icones/icon.png"
  adaptive_icon_background: "lib/recursos/icones/background.png"
  adaptive_icon_foreground: "lib/recursos/icones/foreground.png"    

